# Configurations
title:            Knowslog(지식저장소)
longtitle:        Knowslog(지식저장소)
author:           Sungcheol Shin
email:            scshin88@gmail.com
description: >
  지식저장소

version:          1.0
gitbook_version:  3.2.3

url:              'https://knowslog.github.io'
baseurl:          '/'
rss:              RSS

# bootstrap: use the remote theme for the site itself
remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min: 1
  h_max: 3

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     /assets/gitbook/images/favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: github

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:                /:categories/:year-:month-:day-:title:output_ext

# Disqus comments
# disqushandler:            sighingnow

exclude:
  - _drafts


page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-readme-index
  - jemoji

tracker:
  google_analytics: "G-0KYQBFPZCD"
  
github_username: tourbut